### ISSUE TITLE
use local_setup.py databases instead of static once in .script/databases.mk

### ISSUE THREAD

**Issue by hz-lschick** [mara/mara-example-project-1#27]
I am running mara in several environments: dev, test and live system. They are all running on the same server, they are just separated by the databases defined in `local_setup.py`.

I just figured out that `.script/databases.mk` creates the PostgreSQL databases based on a static name (= resulting in databases I don't need because I use different once in the `local_setup.py` file.

I suggest to adjust `.script/databases.mk` to use the databases defined in `local_config.py` in case the file exist. If not, the static databases names can be used. Maybe even from `local_config.py.example` so that there is a single place in code where the default db names are configured.

**Comment by jankatins** [comment]
That would mean we need a command to output the db config?

**Comment by hz-lschick** [comment]
Right. Or we create a mara_db cli command `create_dbs_if_not_exists" or something similar.
Putting the whole DB connection with username/password out via an CLI command without authentication doesn't sound good to me. Maybe only the server and db name ...

**Comment by jankatins** [comment]
I actually have this implemented on our side: 

```python
# exposed as flask app.cli.ensure-etl-db

@click.command()
def ensure_etl_db():
    """Creates the ETL DB if it doesn't exist"""
    if not auto_create_etl_db_if_not_exist():
        sys.exit(-1)


def auto_create_etl_db_if_not_exist():
    """Creates the ETL DB if it doesn't exist
    """
    import sqlalchemy_utils

    from mara_db.sqlalchemy_engine import engine
    etl_db_engine = engine('dwh')

    try:
        # create database if it does not exist
        if not sqlalchemy_utils.database_exists(etl_db_engine.url):
            sqlalchemy_utils.create_database(etl_db_engine.url)
            print(f'Created database "{etl_db_engine.url!r}"\n')
        else:
            print(f'Database exists "{etl_db_engine.url!r}"\n')
        return True
    except Exception as e:
        print(f'Could not access or create database "{etl_db_engine.url!r}":\n{e}', file=sys.stderr)
        return False
```

**Comment by jankatins** [comment]
I now have it setup like this:

Makefile

```make
# Put local config here into this file:
# the - makes it not fail if the file doesn't exist
-include local_config.mk

# some config stuff -> copy to local_config.mk and change it there!
# keep this in sync with however DBs are configured in local_setup.py
dwh-db ?= bi_dwh
mara-db ?= bi_mara
metabase-metadata-db ?= bi_metabase_metadata
metabase-local-postgresql-user ?= mara
metabase-version ?= v0.35.4
```

This basically means I can change it locally to whatever I want (via `local_config.mk`, added to .gitignore) but I have to manually make the change in two places... 

In my production setup, I don't use the makefiles but do the necessary stuff (run migration, run 'flask app.cli.ensure-etl-db`) by hand in the startup script.

**Comment by jankatins** [comment]
Or another way to unify makefile and setup.py: so why not set env variables in the makefile before running flask and make the default local_setup.py get the values from there?

**Comment by hz-lschick** [comment]
### About deployment

On my production app, I would not like the script to automatically creating a db, but maybe a check if the database exists before calling migration makes sence and is not so dangerous. I call in production the `make` command automatically if it is necessary. I still like calling `make` because it resolves you a lot of trouble dealing with package changes between your local dev and production environment.

Here a small part of my jenkins deploy script:
``` shell
echo "-- Update repository ..."
git checkout master
git fetch

git diff master..origin/master --name-only | grep requirements.txt.freeze > /dev/null
REQUIRE_MAKE=$?
git diff master..origin/master --name-only | grep singer-requirements.txt > /dev/null
REQUIRE_SINGER_INSTALL=$?

git reset --hard origin/master

echo "-- Stop service ..."
systemctl --user stop mara-dev.service

echo "-- Execute make ..."
if [ $REQUIRE_MAKE -eq 0 ]; then
        make
fi
if [ $REQUIRE_SINGER_INSTALL -eq 0 ]; then
        make install-singer-packages
fi

echo "-- Start service ..."
systemctl --user start mara-dev.service
```

### Possible solution via mara-db cli

The solution using `-include local_config.mk` - as you say - makes you deal with the DB names at two places. The idea about using environment variables sounds a bit cumbersome. I'd like straight-forward easy-to-look-at code solutions.

IMHO the solution should be to keep the makefile code as short as possible and move the custom logic into the mara modules. This applies as well to [.script/mara-metabase/metabase.mk](https://github.com/mara/mara-example-project-1/blob/master/.scripts/mara-metabase/metabase.mk), but out of scope for this issue.

I suggest to add cli commands to the mara-db repo to cover the database creation. Here a blue print for db-manage commands:

* `mara_db.create_db` -- creates a database
* `mara_db.ensure_db` -- creates a database if it does not exist
* `mara_db.db_exists` or `mara_db.test_db` -- returns 0 when the database exists, otherwise 1
* `mara_db.drop_db` -- drops a database (could be used in `make cleanup`)
All of these commands could have a `--alias` to set a specific database alias and an `--all` flag to run this for all database connections defined in `local_config.py`

This idea has the benefit that it covers other DBMSs by using the build-in sqlalchemy module. For the build in dev/test, the cli command `mara_db.ensure_db` could be used and in production `mara_db.test_db` (to make sure that the db migration will not crash).

What do you think @jankatins ?

**Comment by jankatins** [comment]
I wouldn't mind these commands and also wouldn't mind if i only have to maintain local_setup.py.example instead of two places. :-) i see more a problem that you still need to output db config as e.g. the metabase.mk file needs a user and potentially a password.

**Comment by martin-loetzsch** [comment]
I think in production you anyway need to do something else. The Makefiles in the example projects are not meant for production deployments. 

We definitely have to improve on the documentation on how to run Mara in production, but we won't change the local workflow for that
